= Software Factory and CI/CD
:navtitle: Home

== Introduction

Welcome to this quick course on the _**Software Factory and CI/CD**_.
This course is the `third` in a series of `six` courses about **Application Platform Delivery**:

* https://link[_Foundations: Developer Experience and GitOps Workflows_, window=browser]
* https://link[_Cloud-Native Development with Dev Spaces_, window=browser]
* _Software Factory and CI/CD_(_This course_)
* https://link[_Application Modernization_, window=browser]
* https://link[_Developer Hub and Platform Engineering_, window=browser]
* https://link[_Trusted Software Supply Chain (TSSC)_, window=browser]

== What's in this course?

By the end of this module, you will be able to deploy, configure, and use Red Hat OpenShift Dev Spaces to develop, build, and deploy applications through integrated GitLab and CI/CD workflows.

Duration: 2.5 hours

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* .. (SME)
* .. (SME)
* Yogita Soni (Content Architect)
* Anna Swicegood (Learning Product Manager)

== Objectives

On completing this course, you should be able to:

Based on the section index, here are concise learning objectives:

### Learning Objectives

By the end of this module, you will be able to:

* Describe the purpose and architecture of Red Hat OpenShift Dev Spaces.
* Explain the key concepts and core components of Dev Spaces.
* Understand how Dev Spaces fits into a Software Factory and supports cloud-native application development.
* Identify the supporting services required to enable an integrated developer platform.
* Deploy and configure the Red Hat OpenShift Dev Spaces Operator on an OpenShift cluster.
* Integrate Dev Spaces with GitLab to enable source code management and developer workflows.
* Create and use Dev Spaces workspaces for cloud-native application development.
* Understand how Continuous Integration (CI) pipelines are triggered and executed from developer workspaces.
* Deploy applications to OpenShift using automated delivery workflows.
* Explain the role of promotion pipelines in advancing applications across development, testing, and production environments.

== Prerequisites

This course assumes that you have the following prior experience:

1. https://training-lms.redhat.com/lmt/clmscoursedetails.prmain?in_sessionId=5034892A2J492834&in_selfContained=N&in_offeringId=57857955&in_tab_group=&in_from_module=CLMSBROWSEV2.PRMAIN[Red Hat OpenShift Container Platform (OCP) Technical Overview] or Kubernetes Basics